# SPDX-License-Identifier: GPL-2.0-only
"""AUTO-GENERATED by finetune/rag_export.py from finetune/rag_db/remediation_rag.db --
DO NOT HAND-EDIT (notes/RemediationRAGPlan.txt "Pipeline shape" step 5).

Per-test_id step breakdown (prose + per-platform commands_template) for
WINDOWS_AUDIT_CATALOG entries whose remediation was drafted+reviewed+AST-validated
through the offline RAG pipeline. windows_audit_parser.py's `_render_solution()`
renders this into the flat `solution` string `_finding()` puts on a finding --
WINDOWS_AUDIT_CATALOG itself keeps ownership of `category`/`description`/`provenance`/
`citations` and the plain-string `solution` fallback for any test_id not (yet)
exported. Re-run the exporter to regenerate:

    python3 finetune/rag_export.py

Generated: 2026-07-22T01:48:21+00:00
Exported entries: 13
"""
from typing import Any, Dict

GENERATED_WINDOWS_AUDIT_SOLUTIONS: Dict[str, Dict[str, Any]] = {   'SMB1-ENABLED': {   'steps': [   {   'text': 'Disable the legacy SMBv1 protocol on this '
                                                 'device.',
                                         'commands_template': {   'windows_powershell': 'Disable-WindowsOptionalFeature '
                                                                                        '-Online '
                                                                                        '-FeatureName '
                                                                                        'SMB1Protocol '
                                                                                        '-NoRestart'}},
                                     'Restart the device to complete the change.',
                                     'If any older devices or software on your network still need '
                                     'SMBv1 (very old printers/NAS boxes are the usual culprits), '
                                     'update or replace those first -- disabling SMBv1 here will '
                                     'break file sharing with them until you do.']},
    'FIREWALL-DOMAIN': {   'steps': [   {   'text': 'Turn on Windows Firewall for the affected '
                                                    'network profile(s).',
                                            'commands_template': {   'windows_powershell': 'Set-NetFirewallProfile '
                                                                                           '-Profile '
                                                                                           'Domain,Public,Private '
                                                                                           '-Enabled '
                                                                                           'True'}}]},
    'FIREWALL-PRIVATE': {   'steps': [   {   'text': 'Turn on Windows Firewall for the affected '
                                                     'network profile(s).',
                                             'commands_template': {   'windows_powershell': 'Set-NetFirewallProfile '
                                                                                            '-Profile '
                                                                                            'Domain,Public,Private '
                                                                                            '-Enabled '
                                                                                            'True'}}]},
    'FIREWALL-PUBLIC': {   'steps': [   {   'text': 'Turn on Windows Firewall for the affected '
                                                    'network profile(s).',
                                            'commands_template': {   'windows_powershell': 'Set-NetFirewallProfile '
                                                                                           '-Profile '
                                                                                           'Domain,Public,Private '
                                                                                           '-Enabled '
                                                                                           'True'}}]},
    'GUEST-ENABLED': {   'steps': [   {   'text': 'Disable the built-in Guest account.',
                                          'commands_template': {   'windows_powershell': 'Disable-LocalUser '
                                                                                         '-Name '
                                                                                         '"Guest"'}}]},
    'RDP-NLA': {   'steps': [   {   'text': "Turn on 'require Network Level Authentication' for "
                                            'Remote Desktop connections.',
                                    'commands_template': {   'windows_powershell': 'Set-ItemProperty '
                                                                                   '-Path '
                                                                                   "'HKLM:\\System\\CurrentControlSet\\Control\\Terminal "
                                                                                   "Server\\WinStations\\RDP-Tcp' "
                                                                                   '-Name '
                                                                                   "'UserAuthentication' "
                                                                                   '-Value 1'}}]},
    'RDP-ENABLED': {   'steps': [   {   'text': 'Disable Remote Desktop connections on this '
                                                'device.',
                                        'commands_template': {   'windows_powershell': 'Set-ItemProperty '
                                                                                       '-Path '
                                                                                       "'HKLM:\\System\\CurrentControlSet\\Control\\Terminal "
                                                                                       "Server' "
                                                                                       '-Name '
                                                                                       "'fDenyTSConnections' "
                                                                                       '-Value '
                                                                                       '1'}}]},
    'WU-AUTOUPDATE': {   'steps': [   {   'text': 'Create the Windows Update policy registry key '
                                                  "if it doesn't already exist.",
                                          'commands_template': {   'windows_powershell': 'New-Item '
                                                                                         '-Path '
                                                                                         "'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' "
                                                                                         '-ErrorAction '
                                                                                         'SilentlyContinue'}},
                                      {   'text': 'Re-enable Automatic Updates.',
                                          'commands_template': {   'windows_powershell': 'Set-ItemProperty '
                                                                                         '-Path '
                                                                                         "'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' "
                                                                                         '-Name '
                                                                                         "'NoAutoUpdate' "
                                                                                         '-Value '
                                                                                         '0'}}]},
    'WU-STALE': {   'steps': [   "Open Settings > Windows Update, select 'Check for updates,' then "
                                 "'Download & install' any updates found. Restart if prompted."]},
    'DEFENDER-RTP': {   'steps': [   {   'text': 'Re-enable Microsoft Defender real-time '
                                                 'protection.',
                                         'commands_template': {   'windows_powershell': 'Set-MpPreference '
                                                                                        '-DisableRealtimeMonitoring '
                                                                                        '$false'}}]},
    'BITLOCKER-OFF': {   'steps': [   'Open Settings > Privacy & Security > Device encryption, and '
                                      'turn Device encryption on. Windows will prompt you to back '
                                      'up your recovery key -- save it somewhere safe (a Microsoft '
                                      "account, printed copy, or USB drive), since you'll need it "
                                      "if you're ever locked out."]},
    'PS-EXECPOLICY': {   'steps': [   {   'text': 'Set the execution policy to RemoteSigned, which '
                                                  'blocks unsigned downloaded scripts but still '
                                                  'allows scripts you write locally.',
                                          'commands_template': {   'windows_powershell': 'Set-ExecutionPolicy '
                                                                                         'RemoteSigned '
                                                                                         '-Scope '
                                                                                         'LocalMachine'}}]},
    'UAC-DISABLED': {   'steps': [   {   'text': 'Re-enable User Account Control.',
                                         'commands_template': {   'windows_powershell': 'Set-ItemProperty '
                                                                                        '-Path '
                                                                                        "'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' "
                                                                                        '-Name '
                                                                                        "'EnableLUA' "
                                                                                        '-Value '
                                                                                        '1'}},
                                     'Restart the device to complete the change.']}}
