# SPDX-License-Identifier: GPL-2.0-only
"""AUTO-GENERATED by finetune/rag_export.py from finetune/rag_db/remediation_rag.db --
DO NOT HAND-EDIT (notes/RemediationRAGPlan.txt "Pipeline shape" step 5).

Overlays `fix_summary`/`steps_template`/`provenance`/`citations` for finding classes
whose remediation was drafted+reviewed+AST-validated through the offline RAG pipeline,
onto core/remediation.py's hand-authored REMEDIATION_CATALOG (which keeps ownership of
`applies_to` and any class not yet exported). Re-run the exporter to regenerate after
approving/validating new entries:

    python3 finetune/rag_export.py

Generated: 2026-07-22T01:48:21+00:00
Exported entries: 15
"""
from typing import Any, Dict

GENERATED_REMEDIATION_ENTRIES: Dict[str, Dict[str, Any]] = {   'downgrade': {   'fix_summary': 'Update {service} to stop its connection protection from being '
                                    'weakened.',
                     'steps_template': [   {   'text': 'Update {service} to version '
                                                       '{fixed_version} or later.',
                                               'commands_template': {   'linux_apt': 'sudo apt-get '
                                                                                     'install '
                                                                                     '--only-upgrade '
                                                                                     '{package}',
                                                                        'linux_dnf': 'sudo dnf '
                                                                                     'upgrade '
                                                                                     '{package}',
                                                                        'linux_pacman': 'sudo '
                                                                                        'pacman -S '
                                                                                        '{package}',
                                                                        'darwin_brew': 'brew '
                                                                                       'upgrade '
                                                                                       '{package}',
                                                                        'windows_winget': 'winget '
                                                                                          'upgrade '
                                                                                          '{package}'}},
                                           {   'text': 'Restart {service} so the update takes '
                                                       "effect, then confirm it's now running "
                                                       '{fixed_version} or later.',
                                               'commands_template': {   'linux_apt': 'sudo '
                                                                                     'systemctl '
                                                                                     'restart '
                                                                                     '{service}',
                                                                        'windows_powershell': 'Restart-Service '
                                                                                              '-Name '
                                                                                              '{service}'}}],
                     'provenance': 'verified:citation',
                     'citations': [   'https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Security_Cheat_Sheet.html',
                                      'https://www.cisa.gov/news-events/news/securing-wireless-networks']},
    'outdated_cms': {   'fix_summary': 'Update {service} to the latest version.',
                        'steps_template': [   'Update {service}, along with its plugins and '
                                              'themes, to the latest version.',
                                              'Turn on automatic updates if your hosting provider '
                                              'supports it.'],
                        'provenance': 'verified:citation',
                        'citations': [   'https://developer.wordpress.org/advanced-administration/security/hardening/']},
    'rce': {   'fix_summary': 'Update {service} to close a remote-code-execution flaw.',
               'steps_template': [   {   'text': 'Update {service} to version {fixed_version} or '
                                                 'later.',
                                         'commands_template': {   'linux_apt': 'sudo apt-get '
                                                                               'install '
                                                                               '--only-upgrade '
                                                                               '{package}',
                                                                  'linux_dnf': 'sudo dnf upgrade '
                                                                               '{package}',
                                                                  'linux_pacman': 'sudo pacman -S '
                                                                                  '{package}',
                                                                  'darwin_brew': 'brew upgrade '
                                                                                 '{package}',
                                                                  'windows_winget': 'winget '
                                                                                    'upgrade '
                                                                                    '{package}'}},
                                     'This flaw can be triggered by anyone on the internet who can '
                                     'reach {service} -- not just someone already on your local '
                                     'network.',
                                     {   'text': "If you don't need {service} reachable from "
                                                 'outside your home network, block port {port} at '
                                                 "this device's firewall.",
                                         'commands_template': {   'linux_apt': 'sudo ufw deny '
                                                                               '{port}',
                                                                  'windows_powershell': 'New-NetFirewallRule '
                                                                                        '-DisplayName '
                                                                                        '"Block '
                                                                                        'port '
                                                                                        '{port}" '
                                                                                        '-Direction '
                                                                                        'Inbound '
                                                                                        '-LocalPort '
                                                                                        '{port} '
                                                                                        '-Protocol '
                                                                                        'TCP '
                                                                                        '-Action '
                                                                                        'Block'}},
                                     {   'text': "If you don't rely on {service} at all, turn it "
                                                 'off until a patch is available.',
                                         'commands_template': {   'linux_apt': 'sudo systemctl '
                                                                               'stop {service}',
                                                                  'windows_powershell': 'Stop-Service '
                                                                                        '-Name '
                                                                                        '{service}'}}],
               'provenance': 'verified:citation',
               'citations': ['https://www.cisa.gov/news-events/news/home-network-security']},
    'cve_other': {   'fix_summary': 'Update {service} to close a known security weakness.',
                     'steps_template': [   {   'text': 'Update {service} to version '
                                                       '{fixed_version} or later.',
                                               'commands_template': {   'linux_apt': 'sudo apt-get '
                                                                                     'install '
                                                                                     '--only-upgrade '
                                                                                     '{package}',
                                                                        'linux_dnf': 'sudo dnf '
                                                                                     'upgrade '
                                                                                     '{package}',
                                                                        'linux_pacman': 'sudo '
                                                                                        'pacman -S '
                                                                                        '{package}',
                                                                        'darwin_brew': 'brew '
                                                                                       'upgrade '
                                                                                       '{package}',
                                                                        'windows_winget': 'winget '
                                                                                          'upgrade '
                                                                                          '{package}'}},
                                           "Review {service}'s configuration against basic "
                                           'hardening checks: (1) it runs under a dedicated, '
                                           'low-privilege account rather than root/administrator; '
                                           '(2) any default admin password, API key, or community '
                                           'string has been changed to a unique, strong '
                                           'credential; (3) it only listens on the network '
                                           'interfaces it actually needs (e.g. 127.0.0.1 for '
                                           'local-only tools) rather than all interfaces.'],
                     'provenance': 'verified:citation',
                     'citations': [   'https://csrc.nist.gov/pubs/sp/800/40/r4/final',
                                      'https://www.cisa.gov/news-events/alerts/2013/06/24/risks-default-passwords-internet',
                                      'https://www.cisa.gov/news-events/news/home-network-security']},
    'open_datastore': {   'fix_summary': 'Set a password on {service} and take it off the open '
                                         'internet.',
                          'steps_template': [   'Set a password on {service} immediately. For the '
                                                'most common exposed datastores:\n'
                                                '- Redis: Add requirepass <password> to redis.conf '
                                                'and restart (or use ACLs for Redis 6+).\n'
                                                '- MongoDB: Add security.authorization: enabled to '
                                                'mongod.conf (or start with --auth) and create a '
                                                'user.\n'
                                                '- Elasticsearch: Ensure xpack.security.enabled: '
                                                'true in elasticsearch.yml and set a password via '
                                                'elasticsearch-reset-password.\n'
                                                '- Memcached: Restrict network access instead (see '
                                                'next step); it does not authenticate meaningfully '
                                                'by default.\n'
                                                '- Other: For any other datastore, check its '
                                                'official documentation to enforce authentication.',
                                                'Make sure {service} only accepts connections from '
                                                'localhost or your home network -- many datastores '
                                                '(like Redis) default to listening on every '
                                                'network interface until explicitly restricted.',
                                                "If you don't recognize {service}, find out what "
                                                'installed it and consider removing it.'],
                          'provenance': 'verified:citation',
                          'citations': [   'https://redis.io/docs/latest/operate/oss_and_stack/management/security/',
                                           'https://www.mongodb.com/docs/manual/tutorial/enable-authentication/',
                                           'https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html',
                                           'https://github.com/memcached/memcached/wiki/SASLHowto']},
    'exposed_admin': {   'fix_summary': 'Lock down the publicly reachable admin login on '
                                        '{service}.',
                         'steps_template': [   'Change the administrator password to a long, '
                                               'unique passphrase immediately, and turn on '
                                               'Two-Factor Authentication (2FA) inside the user '
                                               'profile settings if it is available.',
                                               'Hide or rename the login page if your application '
                                               'supports it. For example, many common tools have '
                                               'simple plugins or settings that let you change the '
                                               'login web address from a generic /admin path to a '
                                               'secret keyword only you know.',
                                               'If you are using a cloud provider (like Cloudflare '
                                               'or a managed website host), turn on their basic '
                                               "'Under Attack Mode' or 'Bot Challenge' settings. "
                                               'This forces a quick security check for visitors '
                                               'before they can even see your login screen.'],
                         'provenance': 'verified:citation',
                         'citations': [   'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/05-Enumerate_Infrastructure_and_Application_Admin_Interfaces',
                                          'https://developers.cloudflare.com/fundamentals/reference/under-attack-mode/']},
    'exposed_source': {   'fix_summary': 'Block public access to the exposed source-control folder '
                                         'on {service}.',
                          'steps_template': [   'Remove or block public access to the exposed .git '
                                                'folder on {service}:\n'
                                                '- Nginx: add location ~ /\\.git { deny all; } '
                                                'inside your server block, then reload (sudo '
                                                'systemctl reload nginx).\n'
                                                '- Apache: add RedirectMatch 404 /\\.git to your '
                                                '.htaccess or vhost config, then reload (sudo '
                                                'systemctl reload apache2).\n'
                                                "- If you don't need git-based deployment on this "
                                                'server, move the .git folder outside the public '
                                                'web root entirely.\n'
                                                "- Other: consult your web server's documentation "
                                                'for blocking access to hidden/dot-directories.',
                                                'Review your deployment process so this folder '
                                                "isn't published again in the future.",
                                                'If passwords or keys were in that code, change '
                                                'them as a precaution.'],
                          'provenance': 'verified:citation',
                          'citations': ['https://cwe.mitre.org/data/definitions/527.html']},
    'bypass': {   'fix_summary': 'Update {service} to close a flaw that could let a login/security '
                                 'check be skipped.',
                  'steps_template': [   {   'text': 'Update {service} to version {fixed_version} '
                                                    'or later.',
                                            'commands_template': {   'linux_apt': 'sudo apt-get '
                                                                                  'install '
                                                                                  '--only-upgrade '
                                                                                  '{package}',
                                                                     'linux_dnf': 'sudo dnf '
                                                                                  'upgrade '
                                                                                  '{package}',
                                                                     'linux_pacman': 'sudo pacman '
                                                                                     '-S {package}',
                                                                     'darwin_brew': 'brew upgrade '
                                                                                    '{package}',
                                                                     'windows_winget': 'winget '
                                                                                       'upgrade '
                                                                                       '{package}'}},
                                        'Use a strong, unique password on {service} either way.'],
                  'provenance': 'verified:citation',
                  'citations': [   'https://www.cisa.gov/news-events/alerts/2013/06/24/risks-default-passwords-internet']},
    'malware': {   'fix_summary': 'Quarantine the detected file and rescan the device.',
                   'steps_template': [   'Disconnect the affected device from the local network '
                                         'and the internet immediately (e.g., unplug the ethernet '
                                         'cable or turn off Wi-Fi) to minimize potential damage '
                                         'and prevent lateral spread.',
                                         'Do not open or execute the flagged file.',
                                         'Delete the file or move it to quarantine using your '
                                         "antivirus software's graphical user interface (GUI).",
                                         "Update your antivirus software's threat definitions, "
                                         'then run a comprehensive full-system scan to check for '
                                         'any secondary payloads or related compromises.',
                                         "Change your critical accounts' passwords immediately "
                                         'afterward -- ideally using a different, trusted device '
                                         '-- in case the malicious file was already active on the '
                                         'system.'],
                   'provenance': 'verified:citation',
                   'citations': [   'https://www.cisa.gov/news-events/news/recovering-viruses-worms-and-trojan-horses']},
    'privesc': {   'fix_summary': 'Update {service} to close a flaw that could let another account '
                                  'gain more access.',
                   'steps_template': [   {   'text': 'Update {service} to version {fixed_version} '
                                                     'or later.',
                                             'commands_template': {   'linux_apt': 'sudo apt-get '
                                                                                   'install '
                                                                                   '--only-upgrade '
                                                                                   '{package}',
                                                                      'linux_dnf': 'sudo dnf '
                                                                                   'upgrade '
                                                                                   '{package}',
                                                                      'linux_pacman': 'sudo pacman '
                                                                                      '-S '
                                                                                      '{package}',
                                                                      'darwin_brew': 'brew upgrade '
                                                                                     '{package}',
                                                                      'windows_winget': 'winget '
                                                                                        'upgrade '
                                                                                        '{package}'}},
                                         'Make sure you recognize and trust every user account '
                                         'that has access to this device.'],
                   'provenance': 'verified:citation',
                   'citations': ['https://csrc.nist.gov/pubs/sp/800/40/r4/final']},
    'infoleak': {   'fix_summary': 'Update {service} to stop it from leaking internal information.',
                    'steps_template': [   {   'text': 'Update {service} to version {fixed_version} '
                                                      'or later.',
                                              'commands_template': {   'linux_apt': 'sudo apt-get '
                                                                                    'install '
                                                                                    '--only-upgrade '
                                                                                    '{package}',
                                                                       'linux_dnf': 'sudo dnf '
                                                                                    'upgrade '
                                                                                    '{package}',
                                                                       'linux_pacman': 'sudo '
                                                                                       'pacman -S '
                                                                                       '{package}',
                                                                       'darwin_brew': 'brew '
                                                                                      'upgrade '
                                                                                      '{package}',
                                                                       'windows_winget': 'winget '
                                                                                         'upgrade '
                                                                                         '{package}'}},
                                          'Avoid exposing {service} directly to the internet if '
                                          "you don't need to.",
                                          {   'text': 'Restrict inbound access to port {port} at '
                                                      'your router/firewall.',
                                              'commands_template': {   'linux_apt': 'sudo ufw deny '
                                                                                    '{port}',
                                                                       'windows_powershell': 'New-NetFirewallRule '
                                                                                             '-DisplayName '
                                                                                             '"Block '
                                                                                             'port '
                                                                                             '{port}" '
                                                                                             '-Direction '
                                                                                             'Inbound '
                                                                                             '-LocalPort '
                                                                                             '{port} '
                                                                                             '-Protocol '
                                                                                             'TCP '
                                                                                             '-Action '
                                                                                             'Block'}},
                                          {   'text': 'On distros using firewalld, remove the port '
                                                      'from the open list.',
                                              'commands_template': {   'linux_dnf': 'sudo '
                                                                                    'firewall-cmd '
                                                                                    '--remove-port={port}/tcp '
                                                                                    '--permanent'}},
                                          {   'text': 'Reload firewalld so the change takes '
                                                      'effect.',
                                              'commands_template': {   'linux_dnf': 'sudo '
                                                                                    'firewall-cmd '
                                                                                    '--reload'}}],
                    'provenance': 'verified:citation',
                    'citations': [   'https://csrc.nist.gov/pubs/sp/800/40/r4/final',
                                     'https://www.cisa.gov/news-events/news/home-network-security']},
    'crash': {   'fix_summary': 'Update {service} to close a flaw that could crash or destabilize '
                                'it.',
                 'steps_template': [   {   'text': 'Update {service} to version {fixed_version} or '
                                                   'later.',
                                           'commands_template': {   'linux_apt': 'sudo apt-get '
                                                                                 'install '
                                                                                 '--only-upgrade '
                                                                                 '{package}',
                                                                    'linux_dnf': 'sudo dnf upgrade '
                                                                                 '{package}',
                                                                    'linux_pacman': 'sudo pacman '
                                                                                    '-S {package}',
                                                                    'darwin_brew': 'brew upgrade '
                                                                                   '{package}',
                                                                    'windows_winget': 'winget '
                                                                                      'upgrade '
                                                                                      '{package}'}},
                                       {   'text': "If you don't need {service}, consider turning "
                                                   'it off.',
                                           'commands_template': {   'linux_apt': 'sudo systemctl '
                                                                                 'stop {service}',
                                                                    'windows_powershell': 'Stop-Service '
                                                                                          '-Name '
                                                                                          '{service}'}}],
                 'provenance': 'verified:citation',
                 'citations': [   'https://csrc.nist.gov/pubs/sp/800/40/r4/final',
                                  'https://www.cisa.gov/news-events/news/home-network-security']},
    'rce_template': {   'fix_summary': 'Update {service} immediately — this flaw could let an '
                                       'attacker run commands on it.',
                        'steps_template': [   'Update {service} to the latest version immediately.',
                                              "If you're not sure how, contact whoever manages "
                                              'this site/service for help.',
                                              'Consider taking {service} offline temporarily until '
                                              "it's updated."],
                        'provenance': 'verified:citation',
                        'citations': [   'https://www.cisa.gov/known-exploited-vulnerabilities-catalog/reducing-significant-risk-known-exploited-vulnerabilities',
                                         'https://csrc.nist.gov/pubs/sp/800/40/r4/final']},
    'default_creds': {   'fix_summary': "Change {service}'s default login immediately.",
                         'steps_template': [   "Log into {service}'s admin page — commonly at "
                                               'http://192.168.1.1, http://192.168.0.1, '
                                               'http://192.168.1.254, http://10.0.0.1, or the '
                                               'address printed on the device itself — and change '
                                               'the default username/password immediately. Use a '
                                               "strong password you don't use anywhere else.",
                                               "Make sure {service}'s login page isn't reachable "
                                               'from the open internet -- restrict it to your home '
                                               'network only.',
                                               "If you don't recognize or use {service}, consider "
                                               'taking it offline.'],
                         'provenance': 'verified:citation',
                         'citations': [   'https://www.cisa.gov/news-events/alerts/2013/06/24/risks-default-passwords-internet']},
    'web_other': {   'fix_summary': 'Review and remediate the flagged issue on {service}.',
                     'steps_template': [   'Review {service} against the linked reference and '
                                           'apply the recommended fix.'],
                     'provenance': 'authored',
                     'citations': []}}
