# SPDX-License-Identifier: GPL-2.0-only
"""Export step (notes/RemediationRAGPlan.txt "Pipeline shape" step 5): reads
finetune/rag_db/remediation_rag.db and writes two generated, do-not-hand-edit
sibling modules that the shipped product imports at runtime:

  - core/remediation_generated.py                -- REMEDIATION_CATALOG overlay
  - scanners/windows/windows_audit_generated.py  -- WINDOWS_AUDIT_CATALOG solution overlay

An entry exports only if:
  - its latest `reviews` row has decision='approved' (the human gate), and
  - every `catalog_step_commands` row belonging to any of its steps has
    ast_validated=1 (an entry with zero command rows trivially satisfies this) --
    review and validation are both required, neither substitutes for the other.

`finding_class` routes to one of the two generated modules by key membership against
the *current* (pre-overlay) REMEDIATION_CATALOG / WINDOWS_AUDIT_CATALOG key spaces,
with one special case: the DB's single "FIREWALL-PROFILE" entry (one combined command
re-enabling all three profiles) expands to WINDOWS_AUDIT_CATALOG's three separate keys
(FIREWALL-DOMAIN/PRIVATE/PUBLIC), since the scanner emits a separate finding per
disabled profile but re-enabling any one of them runs the same safe command.

Run standalone, after finetune/command_ast_validate.py --db has populated
ast_validated on every row this run will consider:

    python3 finetune/rag_export.py

Build-time tooling only, like finetune/command_ast_validate.py -- nothing in
agent.py/core/tools.py imports this module; they import its *output* instead.
"""
import sys
from pathlib import Path
from pprint import pformat
from typing import Any, Dict, List, Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from finetune.rag_db.db import DEFAULT_DB_PATH, get_connection, utcnow_iso

_REPO_ROOT = Path(__file__).resolve().parent.parent
_CORE_REMEDIATION_GENERATED = _REPO_ROOT / "core" / "remediation_generated.py"
_WINDOWS_AUDIT_GENERATED = _REPO_ROOT / "scanners" / "windows" / "windows_audit_generated.py"

_FIREWALL_PROFILE_EXPANSION = ("FIREWALL-DOMAIN", "FIREWALL-PRIVATE", "FIREWALL-PUBLIC")

_CORE_HEADER = '''# SPDX-License-Identifier: GPL-2.0-only
"""AUTO-GENERATED by finetune/rag_export.py from finetune/rag_db/remediation_rag.db --
DO NOT HAND-EDIT (notes/RemediationRAGPlan.txt "Pipeline shape" step 5).

Overlays `fix_summary`/`steps_template`/`provenance`/`citations` for finding classes
whose remediation was drafted+reviewed+AST-validated through the offline RAG pipeline,
onto core/remediation.py's hand-authored REMEDIATION_CATALOG (which keeps ownership of
`applies_to` and any class not yet exported). Re-run the exporter to regenerate after
approving/validating new entries:

    python3 finetune/rag_export.py

Generated: {timestamp}
Exported entries: {count}
"""
from typing import Any, Dict

'''

_WINDOWS_HEADER = '''# SPDX-License-Identifier: GPL-2.0-only
"""AUTO-GENERATED by finetune/rag_export.py from finetune/rag_db/remediation_rag.db --
DO NOT HAND-EDIT (notes/RemediationRAGPlan.txt "Pipeline shape" step 5).

Per-test_id step breakdown (prose + per-platform commands_template) for
WINDOWS_AUDIT_CATALOG entries whose remediation was drafted+reviewed+AST-validated
through the offline RAG pipeline. windows_audit_parser.py's `_render_solution()`
renders this into the flat `solution` string `_finding()` puts on a finding --
WINDOWS_AUDIT_CATALOG itself keeps ownership of `category`/`description`/`provenance`/
`citations` and the plain-string `solution` fallback for any test_id not (yet)
exported. Re-run the exporter to regenerate:

    python3 finetune/rag_export.py

Generated: {timestamp}
Exported entries: {count}
"""
from typing import Any, Dict

'''


def _latest_review_decision(conn, entry_id: int) -> Optional[str]:
    row = conn.execute(
        "SELECT decision FROM reviews WHERE entry_id = ? ORDER BY review_id DESC LIMIT 1",
        (entry_id,),
    ).fetchone()
    return row["decision"] if row else None


def _entry_commands_all_validated(conn, entry_id: int) -> bool:
    row = conn.execute(
        "SELECT COUNT(*) AS n FROM catalog_step_commands csc "
        "JOIN catalog_steps cs ON csc.step_id = cs.step_id "
        "WHERE cs.entry_id = ? AND csc.ast_validated != 1",
        (entry_id,),
    ).fetchone()
    return row["n"] == 0


def _entry_citations(conn, entry_id: int) -> List[str]:
    """Flattens per-entry citation rows to a deduped URL list, preferring a direct
    `citations.url` and falling back to the cited chunk's source URL -- same
    resolution order `insert_citation()`'s docstring documents as the caller's
    choice (db.py)."""
    rows = conn.execute(
        "SELECT c.url AS direct_url, s.url AS source_url FROM citations c "
        "LEFT JOIN chunks ch ON c.chunk_id = ch.chunk_id "
        "LEFT JOIN sources s ON ch.source_id = s.source_id "
        "WHERE c.entry_id = ? ORDER BY c.citation_id",
        (entry_id,),
    ).fetchall()
    urls: List[str] = []
    for row in rows:
        url = row["direct_url"] or row["source_url"]
        if url and url not in urls:
            urls.append(url)
    return urls


def _entry_steps(conn, entry_id: int) -> List[Any]:
    """One list entry per catalog_steps row, ordered by step_order: a bare string if
    the step has no catalog_step_commands rows, else a
    `{"text": ..., "commands_template": {platform_key: command_template}}` dict --
    the shape core/remediation.py's `_fill_steps()` / windows_audit_parser.py's
    `_render_solution()` expect."""
    steps = conn.execute(
        "SELECT step_id, step_template FROM catalog_steps WHERE entry_id = ? ORDER BY step_order",
        (entry_id,),
    ).fetchall()
    out: List[Any] = []
    for step in steps:
        commands = conn.execute(
            "SELECT platform_key, command_template FROM catalog_step_commands "
            "WHERE step_id = ? ORDER BY command_id",
            (step["step_id"],),
        ).fetchall()
        if commands:
            out.append({
                "text": step["step_template"],
                "commands_template": {c["platform_key"]: c["command_template"] for c in commands},
            })
        else:
            out.append(step["step_template"])
    return out


def _write_module(path: Path, header_template: str, var_name: str, data: Dict[str, Any]) -> None:
    header = header_template.format(timestamp=utcnow_iso(), count=len(data))
    body = f"{var_name}: Dict[str, Dict[str, Any]] = {pformat(data, indent=4, width=100, sort_dicts=False)}\n"
    path.write_text(header + body)


def export(db_path=DEFAULT_DB_PATH):
    conn = get_connection(db_path)

    # Import the *current* (pre-overlay) catalogs purely to check key membership --
    # routes each finding_class to whichever generated module it belongs in. This
    # runs before either generated module is (re)written, so it reflects last run's
    # overlay; that's fine, the key spaces this checks against (applies_to routing,
    # WINDOWS_AUDIT_CATALOG's category/description) aren't themselves generated.
    from core.remediation import REMEDIATION_CATALOG
    from scanners.windows.windows_audit_parser import WINDOWS_AUDIT_CATALOG

    remediation_entries: Dict[str, Dict[str, Any]] = {}
    windows_entries: Dict[str, Dict[str, Any]] = {}
    skipped: List[str] = []

    entries = conn.execute(
        "SELECT entry_id, finding_class, fix_summary FROM catalog_entries ORDER BY entry_id"
    ).fetchall()

    for entry in entries:
        finding_class = entry["finding_class"]
        entry_id = entry["entry_id"]

        if _latest_review_decision(conn, entry_id) != "approved":
            skipped.append(f"{finding_class}: no approved review")
            continue
        if not _entry_commands_all_validated(conn, entry_id):
            skipped.append(f"{finding_class}: not all catalog_step_commands rows are ast_validated=1")
            continue

        steps = _entry_steps(conn, entry_id)

        if finding_class == "FIREWALL-PROFILE":
            for key in _FIREWALL_PROFILE_EXPANSION:
                windows_entries[key] = {"steps": steps}
        elif finding_class in WINDOWS_AUDIT_CATALOG:
            windows_entries[finding_class] = {"steps": steps}
        elif finding_class in REMEDIATION_CATALOG:
            citations = _entry_citations(conn, entry_id)
            remediation_entries[finding_class] = {
                "fix_summary": entry["fix_summary"],
                "steps_template": steps,
                "provenance": "verified:citation" if citations else "authored",
                "citations": citations,
            }
        else:
            skipped.append(f"{finding_class}: matches neither REMEDIATION_CATALOG nor "
                            "WINDOWS_AUDIT_CATALOG key space -- not exported")

    conn.close()

    _write_module(_CORE_REMEDIATION_GENERATED, _CORE_HEADER,
                  "GENERATED_REMEDIATION_ENTRIES", remediation_entries)
    _write_module(_WINDOWS_AUDIT_GENERATED, _WINDOWS_HEADER,
                  "GENERATED_WINDOWS_AUDIT_SOLUTIONS", windows_entries)

    return remediation_entries, windows_entries, skipped


def main() -> int:
    remediation_entries, windows_entries, skipped = export()
    print(f"[OK] exported {len(remediation_entries)} REMEDIATION_CATALOG entries -> "
          f"{_CORE_REMEDIATION_GENERATED.relative_to(_REPO_ROOT)}")
    print(f"[OK] exported {len(windows_entries)} WINDOWS_AUDIT_CATALOG entries -> "
          f"{_WINDOWS_AUDIT_GENERATED.relative_to(_REPO_ROOT)}")
    for s in skipped:
        print(f"[SKIP] {s}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
